### ISSUE TITLE
Linking problem

### ISSUE THREAD

**Issue by Noudi03** [MaxOhn/Bathbot#13]
Edge case while linking osu profile. Can't link osu account if the profile name starts and ends with characters that markdown text eg underscore.

**Comment by MaxOhn** [comment]
What happens when you try to link? Is there an error message or something similar?
I don't know how underscores would cause an issue for linking and it's tricky to debug.
If you still have this problem it might be helpful if you join [the discord](https://discord.gg/n9fFstG) so I can check things easier 😃
