### ISSUE TITLE
Wrong indexing on top plays when using `/top` and `<top` commands

### ISSUE THREAD

**Issue by S1n1st3rn3ss** [MaxOhn/Bathbot#15]
**Issue description**
Bathbot's usertop commands have the shown plays numbered starting from zero instead of one
**Expected behaviour:**
top-5 being indexed starting from 1 and ending on 5
**Actual behaviour:**
Indexing starts from 0
![image](https://user-images.githubusercontent.com/49232762/151033011-5da22385-e9aa-48bf-8b86-a01031934151.png)
**Steps to reproduce:**
1) Use the `/top` or the `<top` command

**Comment by MaxOhn** [comment]
Whoops yeah I fixed some other bug and caused this index issue by accident 😄 
Fix is already done, will push it sometime soon.

And just as a side note: Discord made the permission system around slash commands a little weird unfortunately. In order to see external emotes like :SH: from slash commands, the @ everyone role must have the "Use External Emoji" permission.
Just in case you didn't know and have interest and server privilege to change that ;)

**Comment by S1n1st3rn3ss** [comment]
"Use external emoji" perm actually doesn't affect the slash command for some reason. Never noticed that before.

[image](https://user-images.githubusercontent.com/49232762/151361903-1319d367-cb40-488c-b653-969c156688cb.jpeg)

**Comment by MaxOhn** [comment]
Fix for indices is out 👌
