### ISSUE TITLE
Strict Tracking Problem

### ISSUE THREAD

**Issue by Dyslooxia** [MaxOhn/Bathbot#20]
So i just finished playing a map with strict tracking on lazer, when i used <rs it gave me some interesting stats to say the least.
![image_2022-04-23_003012785](https://user-images.githubusercontent.com/6549927/164872687-68dabe8b-afd5-4f1f-838a-70dd90d41d1b.png)

Map: https://osu.ppy.sh/beatmapsets/1031221#osu/2156420
Replay: [Stoof 3 playing 3L - Tiny Little Adiantum (deadman's _Omae Wa Mou_ remix) (Leader) [Shindeiru].zip](https://github.com/MaxOhn/Bathbot/files/8546040/Stoof.3.playing.3L.-.Tiny.Little.Adiantum.deadman.s._Omae.Wa.Mou_.remix.Leader.Shindeiru.zip)

**Comment by MaxOhn** [comment]
Mh interesting find.
The strict tracking mod seems to make sliderballs generate an additional hitresult so you have more n300s, n100s, ... than usual.
The pp calculation compares these hitresults with the total amount of circles, sliders, and spinners in the map and gets confused because the numbers don't line up.

The osu!api unfortunately doesn't provide any info about these new mods yet so there's nothing I can do about it :(

Once the api  provides data about new mods I'll have to rework a bunch of things which would likely solve this too but who knows when that will be. Until then I'll close this one.
