### ISSUE TITLE
tokio-runtime panick.

### ISSUE THREAD

**Issue by TheAmpPlayer** [MaxOhn/Bathbot#462]
So I am new here and my friend wanted me to run a bot for his server.

I got the bot working and running but I am having this issue where whatever command I use, a specific error pop's up for almost every command.
![image_2023-07-15_204145974](https://github.com/MaxOhn/Bathbot/assets/90857134/04b61e54-a15d-47e5-96d0-34ba5972d09b)

I don't really understand much of why this is happening and I tried searching for a solution related to **'tokio-runtime-worker'** but I haven't gotten far. Any help or explanation would be appreciated .

And for reference I don't know much about coding...

**Comment by MaxOhn** [comment]
`tokio-runtime-worker` is just the thread name that panicked, the actual panic is caused by a string failing to be parsed as integer.
It's probably because you haven't specified proper emotes in the .env, you should replace all the `"<:name:id>"` with actual emotes.
You can find some of the emotes here https://github.com/MaxOhn/showerbot/tree/main/emotes
You'll need to upload the images as emotes in some server that your bot is in and then specify those emotes in your .env i.e. the value you get when putting a backslash in front of the discord emote.

Regardless, I should improve the error message on that panic though, will do that :+1:

**Comment by MaxOhn** [comment]
I think I'm fine with uploading all bathbot emotes to this repository, will do soon.

**Comment by TheAmpPlayer** [comment]
> 

Thank you for the quick response and I appreciate the help. It seems that I now have another error after placing the emoji's in. I don't know if I did something wrong or something else.

So here's the .env file: 
![image_2023-07-15_211958565](https://github.com/MaxOhn/Bathbot/assets/90857134/68dbbcd1-53cd-4c83-9cfd-45a99e34969b)

and here's the error code, well nothing much changed but the error went from "InvalidDigit" to "Empty"?
![image_2023-07-15_212128630](https://github.com/MaxOhn/Bathbot/assets/90857134/788e499d-8668-4969-807a-2ec10b8f034d)

**Comment by MaxOhn** [comment]
`"<:name:>"` isn't sufficient for discord, it has to be `"<:name:id>"`. You can get it by using the emote on discord yourself but putting a backslash in front.

**Comment by TheAmpPlayer** [comment]
> `"<:name:>"` isn't sufficient for discord, it has to be `"<:name:id>"`. You can get it by using the emote on discord yourself but putting a backslash in front.

It seems that fixed my issue and the bot's running as expected now.

Thank you very much for the fast responses and making such an amazing project.
