### ISSUE TITLE
incorrect global index

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#671]
> brand new map but theyre #1 on it in both classic and lazer scoring so it cant be from an inconsistency there

Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1229985203880067142/gyPAsCb.png?ex=6631abfc&is=661f36fc&hm=405a0741d7b8de5f89d12896e4e29a0d696ba74227dd205003da80919a1b91fc&)
[Original message by @cd36](https://discord.com/channels/741040473476694159/741057568297975928/1229985204207091763)

**Comment by MaxOhn** [comment]
Determining the score's global index is done by requesting the user's score on the map which contains the global rank by itself and then check if that score equals the recent score. Since that equality check seemed to have passed, the api indeed must've given the global index 2 for whatever reason; perhaps the score wasn't done being processed yet.

Either way, I don't think there's any fixing to do for this on the bot.
