### ISSUE TITLE
100% acc but only S grade

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#687]
> s 100%

[Original message by @rakety.](https://discord.com/channels/741040473476694159/741057568297975928/1231373617758212157)

**Comment by MaxOhn** [comment]
Doesn't look like the grade as it was received from the api got modified at any point but even if it was, both the new and legacy grade calculation for that score result in an `SS`.

The last possible cause I see is that there was an oopsie going on on osu!'s side or the score wasn't processed properly yet or something so that the api stamped the score with an `S` grade.

Don't think there's anything to fix on the bot's end.
