### ISSUE TITLE
"top" command displays different grade than website

### ISSUE THREAD

**Issue by ap-ple** [MaxOhn/Bathbot#725]
![image](https://github.com/MaxOhn/Bathbot/assets/55882424/3866a728-7e2e-47e4-9986-4f6cc00572ec)
![image](https://github.com/MaxOhn/Bathbot/assets/55882424/31532e31-e26e-4a31-b62f-70d2dfcb38e3)

**Comment by yorunoken** [comment]
This is because of the [new changes to how grading works in osu! lazer](https://osu.ppy.sh/wiki/en/Client/Release_stream/Lazer/Gameplay_differences_in_osu%21%28lazer%29).
Bathbot calculates grades with the new forumula, so any play with accuracy below 90% is automatically B rank.

You can change this by using this command: `/config score_data:Stable`
It's intended :>
If you want, you can also enable lazer mode in [osu!s website](https://osu.ppy.sh/) to see it in action.
Note that if you change score data to Stable, you will not be able to see custom dt speed rate for osu!lazer plays.

**Comment by ap-ple** [comment]
oh I gotchu I don't know why I didn't think of that, thanks
